FROM node:20-bookworm-slim

# Install system dependencies
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project config
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY .npmrc ./

# Install pnpm
RUN npm install -g pnpm

# Install deps for web and its workspace dependencies
RUN pnpm install --frozen-lockfile --filter @kallosophia/web...

# Set correct working dir for next dev
WORKDIR /app/apps/web

EXPOSE 3000
CMD ["pnpm", "dev"]
