services:
  db:
    image: postgres:15
    container_name: kallosophia-db
    ports:
      - "5432:5432"
    env_file: .env.db
    networks:
      - kallosophia
    volumes:
      - kallosophia-db-data:/var/lib/postgresql/data

  api:
    image: kallosophia-api:latest
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile.dev
    container_name: kallosophia-api
    ports:
      - "4000:4000"
    volumes:
      - ../../apps/api:/app/apps/api
    depends_on:
      - db
    env_file: .env.api
    command: ["pnpm", "dev"]
    networks:
      - kallosophia

networks:
  kallosophia:

volumes:
  kallosophia-db-data:
