version: "3"
services:
  api:
    image: kallosophia:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://kallosophia:kallosophia@db:5432/kallosophia-dev
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kallosophia
      - POSTGRES_PASSWORD=kallosophia
      - POSTGRES_DB=kallosophia-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
