services:
  db:
    image: postgres:15
    container_name: kallosophia-db
    ports:
      - "5432:5432"
    env_file: .env.db
    volumes:
      - kallosophia-db-data:/var/lib/postgresql/data
    networks:
      - kallosophia

  api:
    image: kallosophia-api:latest
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile.dev
    container_name: kallosophia-api
    ports:
      - "4000:4000"
    volumes:
      - ../../apps/api:/app/apps/api
    depends_on:
      - db
    env_file: .env.api
    command: ["pnpm", "dev"]
    networks:
      - kallosophia

  web:
    image: kallosophia-web:latest
    build:
      context: ../..
      dockerfile: apps/web/Dockerfile.dev
    container_name: kallosophia-web
    working_dir: /app/apps/web
    ports:
      - "3000:3000"
    volumes:
      - ../../apps/web:/app/apps/web
      - ../../package.json:/app/package.json
      - ../../pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ../../pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ../../.npmrc:/app/.npmrc
      - ../../node_modules:/app/node_modules
    depends_on:
      - api
    env_file: .env.web
    command: ["pnpm", "dev"]
    networks:
      - kallosophia

networks:
  kallosophia:

volumes:
  kallosophia-db-data:
